### ISSUE TITLE
Node.js ETL Tool Evaluation

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/unchained#208]
Expectations:
- Evaluate different ETL tools
- Document all your learnings and findings so the whole team can profit

Evaluation Document requirements:
- Build a Feature matrix and map the tools to the features
- Prosa Text for every single ETL Tool do describe pro's and con's
- Summary and Proposal: Argument why we should use tool X
- Put it in a Gist

**Comment by Mikearaya** [comment]
https://gist.github.com/Mikearaya/f72a081ccd07f7438422a04b478c2a4c

most of nodejs(javascript) opensource ETL's have less support with average last commit of 3 years. I think if the basic architecture of an ETL is functioning extending one of these ETL's won't be that much of a hustle  I pick proc-that because of it's a modularized design and it's ease of extendability.

**Comment by schmidsi** [comment]
If any of these tools is really good and inspiring code and just stale, we can think about to take it over. I think we have some contacts at smartive @pozylon @fliptation ?

**Comment by Mikearaya** [comment]
@schmidsi that is what I was thinking
