### ISSUE TITLE
refactor Product-variants

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#22]
While the default apis uf unchained are very self-explanatory, handling product variants is not and is entirely technically driven instead of being business-driven. 

The issues with the current implementation:

- its not obvious what to add to a cart. It seems that adding a ConfigurableProduct to the cart is not intended, yet possible and the api totally suggest that you should be able to do that. After all, its just a `Product` see also https://github.com/unchainedshop/unchained/issues/19
- if you have added a varant to the cart, you don't know its other variants if you add the linked variant's product to the cart
- similar problem for bundles

I would view that entirly from the api perspective, not how it is implemented internaly. So from that perspective i would suggest:

- Everything that is returned by queries `product()` or `products()` can be added to the cart, checked out and ordered
- a product that has variants has property `variants` or similar, where you can lookup the matrix of variants. Every `leave` of this matrix has a `ProductVariant` with some variantId.
- a `ProductVariant` can internally be the same as a Product, but you can't add it to a cart directly. You add it by specifiying the `productId` and some kind of `variantId`. Maybe you can derive the variantId from the options:  "color:blue|size:m"
- a `ProductVariant` can't itself have variants

and maybe (more a braindump)

- a `ProductVariant` has some `baseProduct` field that resolves to the base configurable product
- some fields of a `Product` resolve on a variant, maybe they have an optional argument `variant` (sku, catalogPrice, texts maybe, etc.)
- if no `variantId` is given in that fields (or in `addToCart`), but the product has variants, an error is thrown or a default variant is used, which might use the properties on the base product itself

**Comment by pozylon** [comment]
About the adding of configurableProduct's to a cart:

Assuming you add a ConfigurableProduct to a cart, what if the configurable product changes before you checkout? In that case it would resolve to another concrete product (SKU) with maybe another price, maybe it does not resolve to a concrete one anymore because another color variant has been added meanwhile: 

- T -2 I added X with variantId "color=blue&size=m" (vectors array in today's solution)
- T -1 the admin adds a new variation metric "material" with two options "wood" and "metal"
- T I want to checkout but the system now resolves to two SKU's for color=blue&size=m because the variantId (vectors array) is not unique

I would get around that complexity that way:
- T -2 I added X with variantId "color=blue&size=m" (vectors array in today's solution), system resolves to SimpleProduct Z and adds that to the cart
- T -1 the admin adds a new variation metric "material" with two options "wood" and "metal"
- T Checkout

**Comment by pozylon** [comment]
At the same time, we could still write the "baseProduct -> variant" relationship at the time of cart injection to the db. So if you wanted to reconfigure a ConfigurableProduct you could get that variantId information from there

**Comment by pozylon** [comment]
Matters: https://github.com/unchainedshop/unchained/issues/43

**Comment by pozylon** [comment]
Also discussed here: https://github.com/unchainedshop/unchained/issues/52

**Comment by pozylon** [comment]
Closing in favor of #115
