### ISSUE TITLE
Order.meta resolver private or not?

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#237]
currently Order.meta resolver returns order.context from the db. 

That is probably in cases where you add some meta data to the order that should not be readable by the user of that order

But in other cases you might need this data. I think it should be available as a resolver unless you manually open it up

**Comment by pozylon** [comment]
Suggestion:
1. We migrate order.context from the db to order.meta in the db, that way resolver and db match as the naming is contra-productive in many ways.
2. We add a new field to the order entity that can contain "secrets" like IP addresses, bonity check data, order-specific tokens to third party systems and such.
3. We add a new resolver Order.secrets that is only available for users with special permissions.

Optionally we guard that db field by using aes-256 (https://lollyrock.com/posts/nodejs-encryption/) and a shared key.

**Comment by pozylon** [comment]
> That is probably in cases where you add some meta data to the order that should not be readable by the user of that order

Order.meta is actually intended for use by the user, a User can even edit that field by using updateCart and providing "meta"

**Comment by schmidsi** [comment]
I have a possibly controversial suggestion: My experience with the `Order.meta` field as a developer coming late to the projects was always: What is in there? Because it is just a JSON field, it is also abused as the place where everything can be put that is non-standard. But often, these things are really important for the project but hard to understand, because there is no schema.

So instead of having two fields, a private one and a public one, I suggest to remove them completely. This would force the engineers to properly model these fields in the schema and write the resolvers with the correct business-logic. It is fairly easy to extend the schema in a depending project.

It could remain in the DB, but access to it is part of the project-specific GraphQL interface. That would also comply more with our implicit value: Code over configuration.

What do you think?

**Comment by macrozone** [comment]
@schmidsi totally agree. I also think that unchained should have some strict schema+types for every entity, that developers can extend to their needs

**Comment by pozylon** [comment]
Yes, it feels wrong to have those meta types in Queries and Types, I just did a quick lookup 😬:

- Assortment.meta
- AssortmentProduct.meta
- AssortmentLink.meta
- AssortmentFilter.meta
- Media.meta
- Order.meta
- OrderDelivery.meta
- OrderPayment.meta
- PaymentCredentials.meta
- Product.meta
- Quotation.meta
- SubscriptionPayment.meta
- SubscriptionDelivery.meta

Also I agree with @macrozone that we should have some documented and schema-based way to add custom fields.

**Comment by pozylon** [comment]
If we change it, it's going to brake literally every project but if we don't do it we will propably never change it

**Comment by schmidsi** [comment]
It's the right thing to do. Better now than later. We can start with a deprecation version, that shows warnings in the console. Like this, we have a feeling about the impact. Some of these fields are probably never used (Media.meta maybe?). Then, we can provide a simple snippet how to add these meta-fields on the project level, so the API for the front-ends does not change.

**Comment by pozylon** [comment]
Okay, very good idea, so we could do it in these 3 steps?:

1. Deprecation of meta + maybe some kind of helpers to easily extend existing entities with new custom fields but using meta/context on the db level
2. Add validation on the db level and provide a migration guide in the changelog and snippets to upgrade projects and add information to the docs about how to lock down fields with custom permissions
3. Removal of meta fields on the API level

**Comment by pozylon** [comment]
@Mikearaya This is ready too if you need something to eat :)

**Comment by Mikearaya** [comment]
Removing meta from the API is a straight forward this so far but I've noticed some places where there need to be some workaround

1. Issue dataTrans and stripe plugin depending on `paymentCredentials` context property when using `chargeWithCredentials` helper. one solution would be to have a defined meta field type for payment credential but since this is extendable we don't know what every possible payment provider expects eg. for datatrans require
```
{
        currency: 'CHF',
        expm: '12',
        expy: '21',
        maskedCC: '510000xxxxxx0008',
        pmethod: 'ECA',
      }
```
while stripe

```
{
          customer: 'stripe customer',
          usage: 'off_session',
        }
```

2. The following fields return a computed/transformed meta value and not the raw `meta` data stored though currently, the transformation function is doing nothing but extracting data from the context field.
orderDeliveryPickup.meta
OrderDeliveryShipping.meta
OrderDeliveryShipping.address
OrderPaymentCard.meta
OrderPaymentGeneric.meta
OrderPaymentInvoice.meta

 the obvious solution would be to specify in the documentation that when it comes to order related objects the metadata should be extracted from context field and not the meta field like the rest, even meta field is found in context `this.context.meta`.

Does anyone have an opinion or suggestion on the things mentioned above?

other than that a clean and clear documentation is the major part from what i observed
