### ISSUE TITLE
nothing happens when mutation.updateProductPlan is call with a product not typeOf PLAN_PRODUCT

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#266]
**Describe the bug**
nothing happens when trying to update a product plan of a product that is not the type of PLAN_PRODUCT, shouldn't we inform that the product is not the right type to update its a plan and it should be PLAN_PRODUCT type or something? just a thought

**To Reproduce**
try calling this endpoint with a product ID of not type of PLAN_PRODUCT

**Expected behavior**
if a user called this mutation with a product of the wrong type shouldn't it inform them the product is of a wrong type or something rather than doing nothing silently??

**Comment by pozylon** [comment]
Absolutely, we should throw an exception when a plan product specific mutation is called with a product that has another type. 

Also these mutations can be asserted to some types of products, for example 
- updateProductSupply (only simple products)
- updateProductWarehousing (only simple products)
- createProductVariation (only configurable products)
- addProductAssignment (only configurable products)
- removeProductAssignment (only configurable products)
- createProductBundleItem (only bundle products)
- removeBundleItem (only bundle products)

Same type of assertions should be done here so that only a orderDeliveryId with the correct type can be provided to the mutation:
- updateOrderDeliveryShipping
- updateOrderDeliveryPickUp
- updateOrderPaymentCard
- updateOrderPaymentInvoice
- updateOrderPaymentGeneric

**Comment by pozylon** [comment]
@Mikearaya interested in solving this?

**Comment by Mikearaya** [comment]
@pozylon Issue claimed.

**Comment by pozylon** [comment]
Amazing, merged and closed
