### ISSUE TITLE
Event Tracking Module that allows to connect external Analytics services

### ISSUE THREAD

**Issue by schmidsi** [unchainedshop/unchained#294]
The idea here is, that every Unchained-module has a set of events that are emitted.

Events should be typed. This could be one possibility to type events: https://basarat.gitbook.io/typescript/main-1/typed-event

The worker module has already some sort of events, but it is not perfect:
https://github.com/unchainedshop/unchained/blob/master/packages/core-worker/director.js#L12-L21
https://github.com/unchainedshop/unchained/blob/master/packages/core-worker/director.js#L125

# Step 1: Define events
So for every module, we define a set of events and type them properly:

For example: `core-product` has the following types according to https://docs.unchained.shop/api/entities/#endpoint:
- CREATE
- UPDATE
- DELETE

Or `core-orders` has:
- ADD_PRODUCT
- ADD_DISCOUNT
- CHECKOUT
- CONFIRMED
- ...
(these might not be the best names, I'm open for suggestions here)

# Step 2: Emit events
Then the module's director or module's main collection is extended to emit these events when they occur.

# Step 3: Browsing-events module
To actually be able to track also standard events like "PAGE_VIEW", we need a module that defines these events and exposes GraphQL mutations to actually trigger these events from the front-end.

# Step 4: Example connector to Matomo
Now that we have all modules emitting events, we can now write a conntector-module which listens for these events and puts them in an external service. A good starting point would be Matomo.

# Workflow

* Do Step 1 and 2 ony for `core-orders` and open a Pull request so we all can discuss the introduced patterns
* Do Step 3
* Do Step 4 -> We can ship this feature the for Publicare
* Do Step 1 and 2 for the other modules

**Comment by Mikearaya** [comment]
Making the modules main collection define event is not a good pattern in my opinion and in those cases defining event emitter class on its on might be good. Mainly it will be decoupled from the data.
On the other hand modules that have director class already can define events such as the work module.
So we can either follow the same pattern of defining event emitter per module or define emitter for modules that don't have directors and add event emitter inside each modules director if they have one.

**Comment by pozylon** [comment]
I agree with 1, 3, 4 and the Workflow but like @Mikearaya I think we have to talk about 2 in more details.

I'd go even further and try to encapsulate the event emitting into it's own package and make it a single function call like when you log something. So rather than re-implementing a very basic Event Emitting pattern I'd add an abstraction layer.

The core modules on it's own extend the typesystem so the events are typed at build time + there is some kind of registration function that needs to be called so the registered event enums are also available at runtime.

After you will have dependencies like this:
core-workers depends on core-events
core-products depends on core-events
...

After that it could be some simple functions (`import { emit, subscribe, register } from 'meteor/unchained:core-events'`). 

After implementing Apollo's Subscription feature last week I was investigating the case with Event Emitters and Pub Sub and it's super important for Unchained to support a backing store / technology that can live outside of Unchained. That enables more performance and better memory sharing for certain types of features. See the comments about production usage of memory event emitters here https://www.apollographql.com/docs/apollo-server/data/subscriptions/#pubsub-implementations

So by default `emit` uses an in-memory event emitter but you can also provide Redis, Kafka, ... implementations, that could be be event plugins inside core-events.

Based on that new architecture core-worker's event-listener worker could be refactored in a way that the event listener listens to that event store instead of the current EventEmitter in-memory implementation. A background worker is then capable of processing work based on WORK_ADDED events that are triggered in other instances.

**Comment by Mikearaya** [comment]
@pozylon This is even better since it will solve the duplications

**Comment by schmidsi** [comment]
Yes. Very good idea.

**Comment by schmidsi** [comment]
@Mikearaya This is also related: #118
