### ISSUE TITLE
checkout broken:  orderContext.address is not a function

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#31]
checkoutCart no longer works, it throws this error:

```
error: orderContext.address is not a function

```

**Comment by macrozone** [comment]
i think this is because of https://github.com/unchainedshop/unchained/issues/10

I regret having opened that issue, because i am totally confused now. A delivery should have a delivery address, not a billing address, yet on the order in the db there is a billing address... 

i think there should be no variable, function or object named "address" at all. Either its a `billingAddress` or a `deliveryAddress`.

**Comment by macrozone** [comment]
ok two problems:


```
  billingAddress() {
    return {
      ...this.billingAddress,
      countryCode: this.countryCode,
    };
  },
```

that is not possible, you can't have a helper that has the same name as a property. But removing the helper is also probably problematic, because its unclear whether countryCode is present on the billingAdress or not.


second problem is naming:


```
  send(deliveryContext, orderContext) {
    if (this.status !== OrderDeliveryStatus.OPEN) return;
    const provider = this.provider();
    const address = this.context.address || orderContext.address();
```

orderContext here is of type Order, not of OrderContext, so it should be:

```
  send(deliveryContext, order) {
    if (this.status !== OrderDeliveryStatus.OPEN) return;
    const provider = this.provider();
    const address = this.context.address || order.billingAddress();
```

In untyped languages, it's super important to always use very very good names and never be ambigous. I would suggest to go over all the code and check where *context is used wrong

**Comment by pozylon** [comment]
This was a failed refactoring without tests.

Will be fixed in a new commit to master, I still think it was legit to rename order.address to order.billingAddress, it is the right direction. An OrderDelivery of course has a delivery address, an address on an OrderDelivery context must be a delivery address. The context removes the need of an explicit function name here but not for billingAddress on an order.

If no specific delivery address has been set, unchained assumes that the billingAddress is the address you want the good to be shipped to.

But I can see that the naming of the various contexts, abstractions and parameters are sometimes not good enough to understand quickly.
