### ISSUE TITLE
searchProducts should work without query string or assortmentId

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#445]
**Describe the bug**
currently `Query.searchProducts` does not return any value if it's not provided either `assortmentId` or `queryString`. but it should still return a result without them and should still return a product equal to the specified limit or using the default. 

**current error:**
```
"Query string is required if no assortmentId is provided",
```

this is useful for example when you have a search bar and you want to show some products when a user focuses on it initially.

**To Reproduce**
try searching without specifying `queryString` or `assortmentId`

**Comment by pozylon** [comment]
@Mikearaya searchProducts can be very costly and is not suitable for situations where you want to get every single product that exists. This was the better idea: https://github.com/unchainedshop/unchained/issues/410 which you have brought into https://github.com/unchainedshop/unchained/issues/436 and that ticket is still open.

- searchProducts and searchAssortments should only be used by non-admin apps
- products and assortments are the way to go to build the admin UI because there is no filters that can adjust the result to something.

**Comment by pozylon** [comment]
So because of that, i'm closing this ticket because https://github.com/unchainedshop/unchained/issues/436 will solve it.
