### ISSUE TITLE
Each resolver should have a specific action [FEATURE REQUEST]

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#466]
Currently, action and resolver mapping is done 1 to many where one action can be used for multiple resolvers. this becomes a problem when a you have multiple roles that are  allowed to perform only a certain action.

eg currently `manageProduct` action is applied for creation, update and delete but if there exist two roles where one role can create and update but nod delete and the other can perform all three it's not possible with the current implementation.

**Suggested**
Switch to a 1-to-1 relation between actions and resolvers so

create => createProduct
update => updateProduct
delete =>  deleteProduct

with this role1 will have `allowedActions`: ["createProduct", "updateProduct"]  and role2 will have `allowedActions`: [createProduct, updateProduct, deleteProduct].

refer to  https://github.com/xecutors/unchained-adminui/issues/199

**Comment by pozylon** [comment]
Why don't we examine which actions would make sense on their own, then put together a list. And let's only fix problems we had at customers with this and not artificial ones, the requirement of allowing creation of products without updating has never been raised, but looking at the product methods, we could probably split manageProducts into:

- createProduct
- updateProduct
- removeProduct
- publishProduct

**Comment by pozylon** [comment]
@Mikearaya It's important to note that the developer can still decide to make the updateProduct conditional on a product's status or author by code.

role 1: updateProduct but only for products that are status DRAFT and only when authorId matches logged in user
role 2: updateProduct but unconditionally

**Comment by Mikearaya** [comment]
@pozylon I agree we should keep the conditional assignment of actions but  I don't think it's overkill to make the engine versatile and make the role management future proof it's best to let the developer/project have control over what roles a resolver required. The role management will also be coded first by applying this. 
if that means using the resolver name instead of predefined actions then so be it. I'm pro fully customizable. what do you think

**Comment by pozylon** [comment]
I'm not saying it's overkill to implement, but it will be overkill to use.
The full flexibility is already granted because If needed, a developer can work around the problem by introducing new actions and overwrite existing resolvers to adjust permission checks. We always went the way of "code-first": flexibility yes, but not by customizing.

I thought about this and I don't want to take this too far. We are not fixing a problem (other than helping you maximalize admin ui permissions customizability) if we introduce resolver-level permissions, we are just making it more complicated. Like I said, we could change the default actions based on experience with projects so there might be areas where we have to split up product actions but I don't see any priority here. Let's postpone this, it's really not important.
