### ISSUE TITLE
Fix type error noise when building engine

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#491]
There are a lot of typescript inconsistencies and it's creating a lot of noise when building the engine

**Comment by pozylon** [comment]
While trying to fix the type errors a core design issue popped into my eyes with the new version because whenever I fixed one type issue it cascaded to other type issues in other modules, but why?

Issues:
- There is many places where we pass a field we usually call "context" around (api, services, modules, utility functions). That type "Context" is defined as: Core + Logged In User + Active Locale + HTTP Raw Request/Response.
- But sometimes, core functions get called server-side through workers or events, in those cases, the type does NOT match what is in context because it's not possible to have proper req/res, locale & logged in user data, so it's mainly just the Core + Services layers that is needed.
- Sadly, it's currently not clear to a developer if the code runs based on a user action or triggered via some backend function
- Plugin developers will usually think that the current user is propagated when they write a pricing plugin for example but it's not in some edge cases that can't be easily tested, making unchained projects prone to crashes
- There is no reason to develop something as a service instead of a core function at the moment, it's not clear what should be where and who's responsible for what.

After the weekend and after thinking about this problems a lot I think I know how to fix it and for that reason I need to adjust the Unchained design:

Currently, booting up looks like this and will still be true for the future:
1. Core instantiated at server startup
2. API instantiated with core
3. Every GraphQL Query/Mutation + Webhooks have access to the context

But:
- It should be forbidden to forward the context to services and core as a whole, we should refactor all mutations and queries that currently forward the context to only pass what is required.
- The core modules layer should get injected automatically to every "service" making it clear that when you need to call other services or core module functions, it's propably a service and not a core function you need to write.

So a refactoring will contain some tasks:
1. Move from "Context" to "UnchainedCore" type everywhere but in API, change signatures to explicitly handle cases where a function needs the logged in user or locale data
2. Allow for a workaround to get the current Core Layer with a utils function (inject), this can be done similarily how the contextResolver can be imported at the moment
3. Remove all non-API passing in the Core Layer, use the inject function at the most low level
4. Move core module functionality to services (it's now obvious because you can see where inject is used)

**Comment by pozylon** [comment]
For the moment, I just fix the types as much as I can and fix the rest with some "as Context" workarounds, so this issue can be resolved.
