### ISSUE TITLE
[FEATURE REQUEST] Add a validation step on mutation resolvers

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#570]
It would greatly enhance the functionality to include a validation step for user input before executing the actual mutation resolution process. While most of the validation can be performed using plugins, these are typically triggered after a record is created, which may not always be desirable.

To address this, I propose the implementation of a validation layer that can be extended on a per-project basis, similar to modules and services. This layer would run prior to each resolver and would incorporate a configured validation step. The following code snippet demonstrates a possible implementation:

```
startPlatform({
  validators: {
    createUser: {
      someValidation: () => {},
      anotherValidation: () => {}
    }
  }
})
```

By utilizing this approach, we can ensure that all mutation resolvers undergo a validation process, offering enhanced control and flexibility in handling user input.

**Comment by pozylon** [comment]
Yes it's not quite thought through. There is already a validation layer on the mutations that we use quite regularly, it's the roles/actions that you can extend and change the way you like:

```
// don't allow a user to see his own user data
roles.allRoles.LOGGEDIN.allow(actions.viewUser, () => false)
```

The problem is here, some mutations like createUser don't have any action bound because they were initially defined to be anonymously callable features like forgotPassword or resetPassword.

For the user stuff you could explicitly use the existing accounts options maybe but i think that would not solve your problem:
```
startPlatform({
  options: {
    accounts: {
      someValidation: () => {},
      password: {
        validateNewUser: ({ phoneNumber }) => throw new Error("New users disabled")
      }
    }
  }
})
```

Another option you have is to solve it with a custom context function in startPlatform and throwing from there.


I suppose we extend the roles model to also define actions for the currently anonymous functions:

```
  logout,
  logoutAllSessions,
  loginAsGuest,
  createWebAuthnCredentialCreationOptions,
  createWebAuthnCredentialRequestOptions,
  addPushSubscription: acl(actions.updateUser)(addPushSubscription),
  removePushSubscription: acl(actions.updateUser)(removePushSubscription),
  addWebAuthnCredentials: acl(actions.updateUser)(addWebAuthnCredentials),
...
```

->

```
  logout: acl...(...)(...),
  logoutAllSessions: acl...(...)(...),
  loginAsGuest: acl...(...)(...),
  createWebAuthnCredentialCreationOptions: acl...(...)(...),
  createWebAuthnCredentialRequestOptions: acl...(...)(...),
  addPushSubscription: acl(actions.updateUser)(addPushSubscription),
  removePushSubscription: acl(actions.updateUser)(removePushSubscription),
  addWebAuthnCredentials: acl(actions.updateUser)(addWebAuthnCredentials),
```
